name: Blob storage

on: 
  workflow_dispatch:

env:
  FILENAMEANDPATH: blob-upload-az-cli-1.json
  BLOBSTORAGECONTAINER: test


jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Blob storage
    outputs:
      output1: ${{ steps.org_repos.outputs.data }}    
    steps:
      - uses: actions/checkout@master
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation
      - name: Get Key Vault Secret
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "ghkey" # name of key vault in Azure portal
          secrets: 'serviceprincipal,github-blobstorage-connection-string'  # comma separated list of secret keys to fetch from key vault 
        id: azure_keyvault_secrets # ID for secrets that you will reference
      - name: Set date in env
        run: |
          echo "MY_DATE=$(date +"%FT%H%M")" >> $GITHUB_ENV  
          json='{"commit_id": "b8f2b8b", "environment": "test", "tags_at_commit": "sometags", "project": "someproject", "current_date": "09/10/2014", "version": "someversion"}'
          echo "$json" > ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}}.json
      - name: Upload artifate
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}}.json # name of artifact to create
          path: ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}} # name of existing file/dir to add to artiface                 
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload --file ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}} --container-name test --connection-string "${{ secrets.BLOB_STORE_CONN_STRING }}" --metadata process=mongo