name: GraphQL - who am i

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    env: 
      FILENAME: whoami.json
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.13
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
          save_to_file: 'true'
          ## notice that the file is prepend to previous directory
          save_to_file_name: whoami.json
      - name: List files
        id: list_files
        run: |
            pwd && ls -la 
      - name: Upload artiface
        uses: actions/upload-artifact@v3
        with:
          name: whoami.zip
          path: whoami.json
