name: GraphQL - who am i

on: 
  workflow_dispatch:

jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  
      - name: Var check
        run: |
          echo "${{GITHUB_WORKSPACE}}/temp/whoami.json"  
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.12
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: 'whoami'
          save_to_file: 'true'
          ## notice that the file is prepend to previous directory
          save_to_file_name: $GITHUB_WORKFLOW/whoami.json  
      # - name: View output
      #   run: echo ${{ steps.whoami.outputs.data }} >> whoami.data.action.json  
      - name: List files
        id: list_files
        run: |
            pwd && ls -la 
      - name: Upload artiface
        uses: actions/upload-artifact@v3
        with:
          name: whoami.zip
          path: ${{GITHUB_WORKSPACE}}/temp/whoami.json
