name: GraphQL - who am i

on:
  workflow_dispatch:

env:
  FILENAMEANDPATH: whoami10.json
  BLOBSTORAGECONTAINER: whoami10
  TEMPDIR: temp

jobs:
  graphql:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: GraphQL data scrape
    outputs:
      output1: ${{ steps.whoami.outputs.data }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set date in env
        run: |
          echo "MY_DATE=$(date +"%FT%H%M")" >> $GITHUB_ENV  
      - name: Make temporary directory
        run: |
          mkdir ${{env.TEMPDIR}}                      
      - name: Who Am I
        id: whoami
        uses: dfberry/gh-action-graphql@v1.13
        with:
          github_personal_access_token: ${{ secrets.PAT }}
          query_type: "whoami"
          save_to_file: "true"
          ## notice that the file is prepend to previous directory
          save_to_file_name: ./${{env.TEMPDIR}}/${{env.MY_DATE}}-${{env.FILENAMEANDPATH}}
      - name: List files
        id: list_files
        run: |
          pwd && ls -la
      - name: Print env
        run: printenv          
      - name: Upload artiface
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}}.zip # name of artifact to create
          path: ./${{env.TEMPDIR}}/${{env.MY_DATE}}-${{env.FILENAMEANDPATH}} # name of existing file/dir to add to artiface
      - name: Upload to Blob Storage
        uses: fixpoint/azblob-upload-artifact@v4
        with:
          connection-string: ${{ secrets.BLOB_STORE_CONN_STRING }}
          name: ${{env.MY_DATE}}-${{env.FILENAMEANDPATH}}.zip # artifact name
          path: ./${{env.TEMPDIR}} # path to artifact - a dot means entire directory
          container: ${{env.BLOBSTORAGECONTAINER}} # blob storage container name
