name: Banned files

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main:main

    - name: Check Banned files
      run: |
        bash ./scripts/check-banned-files.sh

