name: Banned files

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main:main

  run: |
    errors=""
    git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
      if grep -Fxq "$file" ./.github/policies/banned-files.txt; then
        errors="${errors}File $file is not allowed with this name and path\n"
      fi
    done
    if [ -n "$errors" ]; then
      echo -e "$errors"
      exit 1
    fi

