name: Banned files

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main:main

    - name: Check Banned files
      run: |
        errors=""
        banned_files=$(tr '[:upper:]' '[:lower:]' < ./.github/policies/banned-files.txt | xargs)
        git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
          file_lower=$(echo "$file" | tr '[:upper:]' '[:lower:]' | xargs)
          if echo "$banned_files" | grep -Fxq "$file_lower"; then
            errors="${errors}File $file is not allowed with this name and path\n"
          fi
        done
        if [ -n "$errors" ]; then
          echo -e "$errors"
          exit 1
        fi

