name: PR file validation

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create failure status check if necessary
      if: ${{ failure() }}
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.REPO_STATUS_PAT }}" \
        -d '{
          "state": "failure",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
          "description": "One or more checks failed",
          "context": "CI"
        }' \
        "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
      continue-on-error: true

    - name: Fetch main branch
      run: git fetch origin main:main

    - name: Check Not Allowed files
      id: check_not_allowed
      run: |
        git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
          if grep -Fxq "$file" ./.github/policies/not-allowed-files.txt; then
            echo "File $file is not allowed"
            exit 1
          fi
        done
      continue-on-error: true

