name: Banned files

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main:main

    - name: Check Not Allowed files
      id: check_not_allowed
      run: |
        git diff --name-only --diff-filter=A origin/main | while IFS= read -r file; do
          if grep -Fxq "$file" ./.github/policies/banned-files.txt; then
            echo "File $file is not allowed with this name and path"
            exit 1
          fi
        done

